### ISSUE TITLE
这个数据库就是个垃圾，一天三蹦

### ISSUE THREAD

**Issue by zeishin** [HotDB-Community/hotdb-documents#2]
这个数据库就是个垃圾，一天三蹦，同一个表生成主键还会重复，写个带主键查询语句数据库奔溃怪开发者写的不规范，问什么回答就是功能都有，要用的时候就说目前不支持。

**Comment by HotDB-Community** [comment]
您好，很抱歉给您造成了不愉快的体验。
关于您说的主键重复和数据库崩溃问题的建议：
主键重复：创建表时需要勾选开启全局唯一约束按钮，能够保证除分片字段以外的唯一键在全局范围保证唯一性
查询语句导致数据库崩溃：需要您提供具体的报错内容及相关日志，以便排查具体原因
另外我们也邮件同步给您对接人的微信，如果方便的话可以微信沟通。

针对具体问题，方便的话可以提供问题复现步骤，我们内部方便验证并及时解决您遇到的困难。
感谢您的支持与理解。

**Comment by zeishin** [comment]
> 您好，很抱歉给您造成了不愉快的体验。 关于您说的主键重复和数据库崩溃问题的建议： 主键重复：创建表时需要勾选开启全局唯一约束按钮，能够保证除分片字段以外的唯一键在全局范围保证唯一性 查询语句导致数据库崩溃：需要您提供具体的报错内容及相关日志，以便排查具体原因 另外我们也邮件同步给您对接人的微信，如果方便的话可以微信沟通。
> 
> 针对具体问题，方便的话可以提供问题复现步骤，我们内部方便验证并及时解决您遇到的困难。 感谢您的支持与理解。

我就是特地来吐槽的，系统上线快1年了，隔三差五数据库宕机，到后面写的sql语句甲方居然要你们审核才能开发，动不动就是语句不规范，表建的语法有问题，有问题就不应该让程序能执行通过，而不是上线有问题了才有说，承认个问题有那么难，同样的代码在其他地方用阿里DRDS、腾讯TDSQL都没有这样问题，连个HINT语法查询居然也要各种申请才能用，各种刁难，不行的话求求你们退出这个市场吧。

**Comment by HotDB-Community** [comment]
您好，非常抱歉让您产生了不愉快的情绪。
方便邮件告知一下您日常的联络方式吗？或者告知下一线对接的人员，我们内部进行核实并处理。
希望双方还是以解决问题为目的，也感谢您提出的宝贵建议。
