### ISSUE TITLE
这个数据库就是个垃圾，一天三蹦

### ISSUE THREAD

**Issue by zeishin** [HotDB-Community/hotdb-documents#3]
呵呵，还删issues

**Comment by zeishin** [comment]
这么大的公司，气量这么小？

**Comment by HotDB-Community** [comment]
您好，您的问题之前我们已经解答，看您三天没有反馈，此问题已经被关闭并删除。
您看是否可以加我们助理微信沟通：251388383
如果不方便的话可以用您的小号联系我们。
希望您反馈的内容还是以具体问题为主，单纯的情绪发泄解决不了问题。

**Comment by zeishin** [comment]
现场反馈有效的话，需要到这里来喷？外面人看的回答就是和其他家的分布式数据库实现差不多，外面人看不到的回答就是你们全面优于阿里腾讯，一问就是有，一用就是要申请，写个语句都要数据库厂商审核。

**Comment by HotDB-Community** [comment]
您好，从您表述的内容来看，可能存在沟通问题。
据和我司现场人员沟通情况，并没有要求SQL需要我司审核的情况，且不存在现场反馈无效的情况。
并且我司上线众多项目，总体运行都很稳定，因此想和您直接沟通，看看是否哪里存在误会。
给您的微信号是我们总部对接人员，非现场人员，并且从您提出的内容来看，没有看到您反馈的具体SQL，是否可以和总部对接人员详细交流具体问题呢？

**Comment by zeishin** [comment]
沟通有问题？就是和你们的人学的，回答就是，xx那个地方用的都很好，都没这样的问题，现在信息这么发达，一去打听也是经常崩溃，估计你们内部也这样，上层一问底下的就是很好很稳定。

**Comment by HotDB-Community** [comment]
您好，我们一直本着解决问题的目的想和您取得联系，您能告知一下为什么持续拒绝沟通吗？持续拒绝沟通的话，问题始终无法得到解决。
如果只是发泄情绪的话，并不会对事情的好转产生任何帮助。
与我们沟通具体的问题，或许能改善您的体验，为什么不尝试一下呢？
